### ISSUE TITLE
Investigate feasibility of enhancing JSON-Java to support BigDecimal and BigInteger 

### ISSUE THREAD

**Issue by FritzMock** [douglascrockford/JSON-java#126] opened 2015-05-19 14:59 UTC
Following test-code will not produce expected results, the array-elements of type BigDecimal will be incorrectly quoted. I guess other Number types like BigInteger will fail too.

Number[] foo = new Number[5];
foo[0] = BigDecimal.ZERO;
foo[1] = new Integer( 1 );
foo[2] = new BigDecimal( 1.2 );
foo[3] = new Integer( 3 );
foo[4] = new BigDecimal( 4 );
JSONStringer s = new JSONStringer();
s.object();
s.key( "bar" );
s.value( foo );
s.endObject();
System.out.println( s.toString() );

I located the problem in the JSONObject.wrap(Object object) method line 1547 (ff) where the half dozen "instanceof <someWrappedPrimitiveNumberType>" comparision should be replaced by a single "intanceof Number".

(The original code where i stumbled into this bug produces "highcharts" from various oracle database queries and of course, highcharts fails to produce charts from strings. Using Doubles is also no option ...)

**Comment by FritzMock** [comment] 2015-05-20 08:33
One more comment about the condition in question, NULL is an instanceof JSONObject:

object instanceof JSONObject || [...] || NULL.equals(object)

If the instanceof is false, the call to the equals method just adds pointless computation overhead.
(Calling equals first will also -most certainly- not provide any performance benefit.)

**Comment by johnjaylward** [comment] 2015-05-20 13:09
And this is why Sean is asking for help on code coverage tests :D Thanks for that.

**Comment by johnjaylward** [comment] 2015-05-20 13:13
I just checked the source and Null is not an instance of JSONObject. if is an Internal class of JSONObject. The instanceof check will fail is object is of type Null.

**Comment by FritzMock** [comment] 2015-05-20 15:47
Sorry, you are right! I cannot recall, how I came on that wrong track ...

**Comment by stleary** [comment] 2015-06-12 17:28
To support BigDecimal and BigInteger, what would have to occur in terms of:
* API changes 
* Behavior changes
* Files touched
* Effects on existing applications
* Interoperability
* Unit test changes

**Comment by douglascrockford** [comment] 2015-06-12 17:44
The package was written before Big was invented. I am not opposed to adding Big
support if we can absolutely guarantee that there is no possibility that any
existing application will be broken or inconvenienced by the change.

**Comment by stleary** [comment] 2015-06-13 15:58
Thanks for clarifying, added a constraint to the issue statement.

**Comment by stleary** [comment] 2015-06-18 01:43
See JSONObjectTest bigNumberOperations()
Results:
* JSONObject(BigInteger|BigDecimal) is broken and should be fixed. 
* jsonObject.getBigInteger(String), jsonObject.getBigDecimal(String) should be implemented. 
* jsonObject.put(String, BigInteger|BigDecimal) works correctly.
* jsonObject.numberToString(BigInteger|BigDecimal) works correctly.
* jsonObject.stringToValue(BigInteger|BigDecimal) does not work correctly, but is not completely broken. It is possible users have come to expect this behavior.
* jsonObject.wrap(BigInteger|BigDecimal) turn the values into strings, but this is the advertised behavior. Probably not a bug.

**API changes:** My proposal is to fix JSONObject(BigInteger|BigDecimal) and implement the missing get() methods. I don't recommend any other changes at this time. 
**Behavior changes:** Only the ctors will be changed. The current behavior does not seem to be what users might reasonably expect. 
**Files touched:** JSONObject.java
**Effect on existing apps:** The JSONObject bean ctor will no longer be invoked for BigInteger and BigDecimal. As a result, BigInteger will no longer store a meaningless value and BigDecimal will no longer be empty.
**Interoperability:** I don't anticipate any effect on interoperability. Serialization is not changed. It was always possible to store BigInteger and BigDecimal via put(String, Object) and serialize them as numbers.
**Unit test changes:** JSONObjectTest bigNumberOperations() will be modified to test the new behavior. There are a few other asserts in this file that will need to be updated.

Please let me know if you notice anything I missed, or miss-stated. Will leave this up for a few days and proceed with a fix if there are no objections.

**Closed** 2015-07-11 17:52 UTC
